line-length = 88
target-version = 'py313'

[lint]
select = ['ALL']
ignore = [
    'ARG005',
    'ANN',
    'B905',
    'D',
    'E741',
    'ERA001',
    'N999',
    'PLR2004',
    'PT013',
    'PTH123',
    'S101',
    'T201',
]
